feat: add udc_functions.sh and modify src file structure
radxa-pkg/radxa-otgutils pull request #13
Opened 2024-07-26 02:37 UTC by CodeChenL

2024-07-26 06:17 UTC, RadxaYuntian reviewed
CI挂了，先看看怎么回事

2024-07-29 08:55 UTC, RadxaYuntian requested changes

2024-07-29 08:55 UTC, RadxaYuntian commented on debian/install
目前没必要移动代码结构，新的文件加一个新的install路径就好

2024-07-29 08:55 UTC, RadxaYuntian commented on src/usr/lib/radxa-otgutils/udc_functions.sh
在make build里面加一个步骤，通过debian里面有的service文件来生成一个json，放到usr/share里面吧

2024-07-29 11:12 UTC, RadxaYuntian requested changes

2024-07-29 11:12 UTC, RadxaYuntian commented on Makefile
> +	find debian -maxdepth "1" -name "*.service" | while IFS= read -r file; \
```suggestion
build: build-man build-doc build-data

.PHONY: build-data
build-data: services.json

services.json:
	find debian -maxdepth "1" -name "*.service" | while IFS= read -r file; \
```

2024-07-29 11:12 UTC, RadxaYuntian commented on Makefile
make clean 也要删掉这个文件

2024-07-29 11:12 UTC, RadxaYuntian commented on Makefile
> +	done | jq --raw-input '[., inputs] | map(select(. != "" and . != "radxa-udc@"))' > services.json
`ls debian/*.service | jq --raw-input '[., inputs] | map(ltrimstr("debian/radxa-otgutils.") | rtrimstr(".service"))' > service.json`
忘记了我们没有udc服务了

2024-07-29 12:45 UTC, RadxaYuntian requested changes

2024-07-29 12:45 UTC, RadxaYuntian commented on Makefile
这个还没改

2024-07-30 02:03 UTC, RadxaYuntian requested changes
make clean需要清除services.json

2024-07-30 07:55 UTC, CodeChenL commented
> make clean需要清除services.json

现在make clean就是能清掉services.json呀

2024-07-30 09:03 UTC, RadxaYuntian requested changes

2024-07-30 09:03 UTC, RadxaYuntian commented on Makefile
> +services.json:
跟别target的一样加上对应的变量，另外这个可以设成phony,每次编译都重建

2024-07-31 02:35 UTC, RadxaYuntian requested changes
squash

2024-07-31 02:52 UTC, RadxaYuntian requested changes
单这一个是肯定关不掉radxa-pkg/rsetup#72，还要那边适配

2024-07-31 02:59 UTC, CodeChenL commented
> 单这一个是肯定关不掉[radxa-pkg/rsetup#72](https://github.com/radxa-pkg/rsetup/issues/72)，还要那边适配

rsetup 已经提了pr https://github.com/radxa-pkg/rsetup/pull/73

2024-07-31 03:01 UTC, RadxaYuntian commented
但你这个commit消息合并后就会关掉那边的issue，而那应该是由73再去关的

2024-07-31 03:14 UTC, CodeChenL commented
> 但你这个commit消息合并后就会关掉那边的issue，而那应该是由73再去关的

已去掉closes关键词

2024-07-31 03:23 UTC, RadxaYuntian approved these changes

2024-07-31 03:23 UTC, merged