Add multi-UDC support
radxa-pkg/radxa-otgutils pull request #7
Opened 2024-01-23 03:25 UTC by CodeChenL

2024-01-23 03:36 UTC, RadxaYuntian requested changes
不要删掉错误处理啊！

2024-01-23 03:36 UTC, RadxaYuntian commented on debian/radxa-otgutils.radxa-adbd@.service
> -ExecStart=/usr/sbin/radxa-otgutils adbd start
description需要修改：`Enable adbd on %I`
https://github.com/radxa-pkg/rsetup/blob/main/debian/rsetup.rsetup-hciattach%40.service#L2

2024-01-23 03:36 UTC, RadxaYuntian commented on debian/radxa-otgutils.radxa-usbnet@.service
> -ExecStart=/usr/sbin/radxa-otgutils usbnet start
修改description

2024-01-23 03:36 UTC, RadxaYuntian commented on debian/rules
> +	dh_installsystemd --no-enable --no-start --name=radxa-usbnet@
带@的应该是不会自动开启：https://github.com/radxa-pkg/rsetup/blob/main/debian/rules#L12-L14

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    echo "Usage: $0 {start|stop|restart}"
这个修改少了$1和$3的说明，另外习惯约定<>里面是必须参数，[]里面是可选参数

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> +UDC="$3"
按照顺序来，$3在$2后面

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> -case "$1" in
任何程序都要检查用户输入啊

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> +            killall adbd
不要用killall，会误杀同名进程
start-stop-daemon有什么问题

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC" || true
这边不是说了任何时候开启都先写空再写UDC么？

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> -    UDC="$(basename "$(find /sys/class/udc -maxdepth 1 -mindepth 1 | sort | head -1)")"
要检查用户输入的UDC是否是合法值，如果不是就退出并给予对应的错误消息

2024-01-23 03:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        rmdir "/sys/kernel/config/usb_gadget/$UDC"
不能`rm -rf`么？

2024-01-23 03:42 UTC, CodeChenL commented on src/radxa-otgutils
> +    echo "Usage: $0 {start|stop|restart}"
这里第二个提交有修改

2024-01-23 03:44 UTC, RadxaYuntian commented
另外这个PR现在相当于一个breaking change。用户目前的系统里面adbd和usbnet应该是不会自动开启的，但实际的镜像里面好像还是自动打开了。可能要看看目前这个行为是什么原因导致的

2024-01-23 03:44 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    echo "Usage: $0 {start|stop|restart}"
所以我已经resolve了

2024-01-23 03:45 UTC, CodeChenL commented
> breaking chang

是的，我也好奇

2024-01-23 06:25 UTC, CodeChenL commented on src/radxa-otgutils
> +            killall adbd
脚本模式用start-stop-daemon 杀不死adbd

2024-01-23 06:27 UTC, RadxaYuntian commented on src/radxa-otgutils
> +            killall adbd
你看一看adbd的pid是不是和pidfile里面的一样

2024-01-23 06:27 UTC, CodeChenL commented on src/radxa-otgutils
> +UDC="$3"
这里是顺序执行，先处理$2的话，就进start这些函数里了，＄UDC就会没赋值

2024-01-23 06:28 UTC, CodeChenL commented on src/radxa-otgutils
> +            killall adbd
pidfile是空的

2024-01-23 06:31 UTC, RadxaYuntian commented on src/radxa-otgutils
> +UDC="$3"
那可能这里的命令行处理需要改进一下了

2024-01-23 06:36 UTC, RadxaYuntian commented on src/radxa-otgutils
> +            killall adbd
手动运行一下start-stop-daemon启动服务看一看，可能要我们自己用--make-pidfile和--remove-pidfile来创建pidfile
参考https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html

2024-01-23 06:37 UTC, CodeChenL commented on src/radxa-otgutils
> +    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC" || true
如果本来就是空的，再写空也会报错

2024-01-23 06:54 UTC, CodeChenL commented on src/radxa-otgutils
> +        rmdir "/sys/kernel/config/usb_gadget/$UDC"
不行要依次删除

2024-01-23 07:25 UTC, RadxaYuntian requested changes

2024-01-23 07:25 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    if [[ ! $(< "/sys/kernel/config/usb_gadget/$UDC/UDC") == "" ]] ;
```suggestion
    if [[ -n $(cat "/sys/kernel/config/usb_gadget/$UDC/UDC") ]]
```
尽量用一些常见的bash表达。

2024-01-23 07:25 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC" || true
```suggestion
        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
```
这个true是之前无法多次写入时加入的，现在需要保证我们写入这个操作是必须成功的，才能确保配置成功打开

2024-01-23 07:25 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC" || true
```suggestion
    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
```

2024-01-23 07:25 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    sleep 1
这里为什么要sleep

2024-01-23 07:25 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
start和stop都会在这个目录里面进行操作，要用flock把这个目录锁住，再进行后面的操作

2024-01-23 10:18 UTC, RadxaYuntian requested changes

2024-01-23 10:18 UTC, RadxaYuntian commented on src/radxa-otgutils
> +            start-stop-daemon --start --oknodo -m --pidfile /var/run/adbd.pid --startas /usr/bin/adbd --background
这种不常见的命令用长选项，提高可读性

2024-01-23 10:18 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    exec 7<"/sys/kernel/config/usb_gadget/$UDC" && flock 7 && echo "Locked: /sys/kernel/config/usb_gadget/$UDC" || echo "Failed to lock: /sys/kernel/config/usb_gadget/$UDC"
锁100吧。
另外这里没必要用&&||连接命令，如果锁不上直接通过bash -e错误结束脚本运行

2024-01-23 10:18 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    exec 7<&- && echo "Unlocked: /sys/kernel/config/usb_gadget/$UDC" || echo "Failed to unlock: /sys/kernel/config/usb_gadget/$UDC"
这里也没必要&&||

2024-01-23 10:18 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    lockdir
锁应该是以整个start/stop为粒度进行锁定。考虑到锁可能不能把/sys/kernel/config/usb_gadget/$UDC在function_stop里面删除。看看不删除的话可不可以正常deinit

2024-01-23 10:21 UTC, CodeChenL commented on src/radxa-otgutils
> +    lockdir
目前function_stop能正常删除，因为在同一个shell进程里？

2024-01-23 10:22 UTC, CodeChenL commented on src/radxa-otgutils
> +    lockdir
start/stop为粒度的话，会出现/sys/kernel/config/usb_gadget/$UDC还没创建就lockdir，会失败

2024-01-23 10:24 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    lockdir
也许吧，总之先留着看看，不然上锁会比较麻烦：
1. 服务start创建了目录
2. 服务stop获取了锁
3. 服务start申请锁，但被stop阻塞
4. stop删除目录，释放了锁
5. start现在还能申请锁么？

2024-01-23 10:26 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    lockdir
要把创建目录提出来，再上锁
另外想了下start在上面的情况也可以拿到锁，因为linux文件删除是在所有句柄都被释放的时候才发生，但这时候这个目录会是不可见的，再次使用这个udc的话会因为udc已经被初始化了无法再次使用

2024-01-23 10:28 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    lockdir
啊不对，应该是可以拿到锁，但/sys/kernel/config/usb_gadget/$UDC路径不存在，所以后续创建文件的操作会失败。所以这个目录不能删

2024-01-23 10:30 UTC, CodeChenL commented on src/radxa-otgutils
> +    lockdir
你的意思是不deinit目录，只删functions吗

2024-01-23 10:47 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    lockdir
保留/sys/kernel/config/usb_gadget/$UDC目录，只删除里面的内容

2024-01-24 02:06 UTC, CodeChenL commented
> 另外这个PR现在相当于一个breaking change。用户目前的系统里面adbd和usbnet应该是不会自动开启的，但实际的镜像里面好像还是自动打开了。可能要看看目前这个行为是什么原因导致的

看了一下[构建日志](https://pipelinesghubeus5.actions.githubusercontent.com/cU8iChQcD0S9sfEFRXQ28KrQfllMSLiCvQhs0idOIi7qazz2fT/_apis/pipelines/1/runs/53/signedlogcontent/10?urlExpires=2024-01-24T02%3A03%3A51.9068024Z&urlSigningMethod=HMACV1&urlSignature=CqBh6Pv84o3Fy1gp9w7A%2FA2GTzDpS3kFQcGAK4boRSM%3D)搜索'Created symlink'字段，没找到'radxa-adbd'和'radxa-usbnet‘

2024-01-24 02:07 UTC, CodeChenL commented
> > 另外这个PR现在相当于一个breaking change。用户目前的系统里面adbd和usbnet应该是不会自动开启的，但实际的镜像里面好像还是自动打开了。可能要看看目前这个行为是什么原因导致的
> 
> 看了一下[构建日志](https://github.com/radxa-build/rock-5b/commit/d944d66fb1fbe895cf9762a97e61bbb521348c12/checks/20334686876/logs)搜索'Created symlink'字段，没找到'radxa-adbd'和'radxa-usbnet‘

2024-01-24 07:58 UTC, RadxaYuntian requested changes
1. 如果github上面有代码修改建议的话，可以在网页上面直接引用，这样会自动关闭修改建议对应的话题
2. 用shellcheck检查一下

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" ];
```suggestion
    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC" ];
```
另外这整个函数可以加到lockdir里面，否则现在直接执行stop的话会无法lock

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    exec 100<"/sys/kernel/config/usb_gadget/$UDC" && flock 100
```suggestion
    exec 100<"/sys/kernel/config/usb_gadget/$UDC"
    flock 100
```
没有必要&&。shebang有传入-e参数，如果出错会直接终止脚本

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +lockdir() {
```suggestion
lock_udc() {
```
名字改一下，表示我们是针对控制器上锁

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +unlockdir() {
```suggestion
unlock_udc() {
```

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    pushd "/sys/kernel/config/usb_gadget/$UDC"
`configs/r.1/strings/0x409/configuration`看上去是一个可自定义的字段：https://www.linux4sam.org/bin/view/Linux4SAM/USBGadgetConfig?skin=print.myskin
改成`USB Composite Device`试试，因为我们现在有可能不会开启adb

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
```suggestion
        rm -rf "/sys/kernel/config/usb_gadget/$UDC"/*
```

2024-01-24 07:58 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
我记得不是要先写入一个空字符串么？

2024-01-24 08:13 UTC, RadxaYuntian commented
有冲突，需要rebase一下你的pr

2024-01-24 09:08 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
不要删这个目录

2024-01-24 09:11 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
为什么这里不用写入空字符串

2024-01-24 11:40 UTC, CodeChenL commented on src/radxa-otgutils
> +        rm -rf "/sys/kernel/config/usb_gadget/$UDC/*"
这样也不行，会提示Operation not permitted，只能rmdir "/sys/kernel/config/usb_gadget/$UDC"，再mkdir了

2024-01-24 11:40 UTC, CodeChenL commented on src/radxa-otgutils
> +        mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
这样不行我试过了

2024-01-24 11:40 UTC, CodeChenL commented on src/radxa-otgutils
> +        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
因为前面卸载funtion,会自动清空udc,所以不用写空

2024-01-24 11:40 UTC, CodeChenL commented on src/radxa-otgutils
> +        mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
你的意思是，把93 94行删了就行是吗

2024-01-24 11:40 UTC, CodeChenL commented on src/radxa-otgutils
> +        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
> 为什么这里不用写入空字符串

因为前面卸载funtion,会自动清空udc,所以不用写空

2024-01-24 12:03 UTC, RadxaYuntian requested changes

2024-01-24 12:03 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        rmdir "/sys/kernel/config/usb_gadget/$UDC/strings/0x409"
需要判断目录是否存在

2024-01-24 12:03 UTC, RadxaYuntian commented on src/radxa-otgutils
> +    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
这个要单独做一个函数

2024-01-24 12:03 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC"
这里要用上面的写udc函数。有时候udc里面不是空的

2024-01-24 12:03 UTC, RadxaYuntian commented on src/radxa-otgutils
>              sleep 1
```suggestion
            sleep 0
```
测试后发现0也是可以保证UDC后续可以成功设置

2024-01-25 06:45 UTC, RadxaYuntian requested changes

2024-01-25 06:45 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        if [ -e "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" ];
你肯定是检查后面删除的目录是否存在，存在再删啊。这个检查和后面的删除完全没有关系

2024-01-25 06:45 UTC, RadxaYuntian commented on src/radxa-otgutils
> +add_udc()
```suggestion
enable_udc()
```
add_udc说的不是太明白

2024-01-25 06:45 UTC, RadxaYuntian commented on src/radxa-otgutils
> +        echo "Unregister: /sys/kernel/config/usb_gadget/$UDC"
这些新增的调试消息还是删掉了吧，没什么实际意义

2024-01-25 08:16 UTC, RadxaYuntian approved these changes

2024-01-25 08:16 UTC, merged

2024-01-25 08:31 UTC, CodeChenL commented
这不需要压缩 commit 吗，我想着最后要压缩，所以用了中文commit信息

2024-01-25 08:35 UTC, RadxaYuntian commented
我这边squash了，但commit消息还是尽量用英文